version: '3.5'

services:
  nogales_inventory:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-server
    ports:
      - '4242:4242'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nogales_inventory
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=nogales_inventory
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/var/lib/mongodata/data
    networks:
      - nogales_inventory

volumes:
  mongodata:

networks:
  nogales_inventory:
